import { BarChart3, BellOff, Focus, ShieldCheck } from "lucide-react";

export function AppIcon({ className = "" }: { className?: string }) {
  return <div className={`relative grid place-items-center overflow-hidden rounded-[28%] bg-gradient-to-br from-[#9b58d4] to-[#512078] shadow-2xl shadow-primary/30 ${className}`}><div className="absolute -right-4 -top-4 h-16 w-16 rounded-full bg-white/15 blur-xl" /><span className="relative text-[0.38em] font-black tracking-[-0.08em] text-white">dS</span></div>;
}

const data = [{label:"Focus",value:"42m",icon:Focus},{label:"Blocked",value:"18",icon:ShieldCheck},{label:"Muted",value:"36",icon:BellOff}];

export function PhonePreview({ variant = "home" }: { variant?: "home" | "focus" | "insights" }) {
  return <div className="relative mx-auto w-[240px] rounded-[2.7rem] border-[7px] border-[#262626] bg-[#0d0d0d] p-3 shadow-2xl shadow-black/60"><div className="absolute left-1/2 top-2 z-10 h-5 w-20 -translate-x-1/2 rounded-full bg-[#262626]" /><div className="min-h-[470px] overflow-hidden rounded-[2rem] border border-white/5 bg-gradient-to-b from-[#1b1023] to-[#0b0b0b] p-4 pt-10"><div className="mb-8 flex items-center justify-between text-[10px] text-white/60"><span>9:41</span><span>deScroll</span></div>
    {variant==="home"&&<><p className="text-xs text-white/50">Good morning</p><p className="mt-1 text-2xl font-semibold">Stay intentional.</p><div className="mt-8 rounded-2xl border border-primary/30 bg-primary/15 p-4"><div className="flex items-center gap-2 text-xs text-primary"><Focus className="h-4 w-4" /> Focus session</div><p className="mt-3 text-3xl font-bold">42:18</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-2/3 rounded-full bg-primary" /></div></div><div className="mt-5 grid grid-cols-3 gap-2">{data.map(({label,value,icon:Icon})=><div key={label} className="rounded-xl border border-white/5 bg-white/5 p-2 text-center"><Icon className="mx-auto h-3.5 w-3.5 text-primary" /><p className="mt-2 text-sm font-semibold">{value}</p><p className="text-[8px] text-white/40">{label}</p></div>)}</div></>}
    {variant==="focus"&&<div className="flex min-h-[340px] flex-col items-center justify-center text-center"><div className="grid h-20 w-20 place-items-center rounded-full border border-primary/40 bg-primary/15"><Focus className="h-9 w-9 text-primary" /></div><p className="mt-7 text-4xl font-bold">24:36</p><p className="mt-2 text-xs text-white/50">Deep focus in progress</p><div className="mt-10 rounded-xl border border-white/10 bg-white/5 px-6 py-3 text-xs text-white/70">End session</div></div>}
    {variant==="insights"&&<><p className="text-xs text-white/50">Weekly report</p><p className="mt-1 text-2xl font-semibold">Build better habits</p><div className="mt-8 flex h-40 items-end gap-2 rounded-2xl border border-white/5 bg-white/[0.03] p-4">{[38,61,45,76,54,84,68].map((height,index)=><div key={index} className="flex-1 rounded-t bg-gradient-to-t from-primary/40 to-primary" style={{height:`${height}%`}} />)}</div><div className="mt-5 rounded-2xl border border-white/5 bg-white/5 p-4"><div className="flex items-center gap-2 text-xs"><BarChart3 className="h-4 w-4 text-primary" /> Screen time</div><p className="mt-3 text-2xl font-bold">Weekly insights</p><p className="mt-1 text-[10px] text-emerald-400">Understand your usage patterns</p></div></>}
  </div></div>;
}
